set_property SRC_FILE_INFO {cfile:{C:/Users/User/Documents/4th SEM/DSD/LAB/Lab1_ANDGate.xdc} rfile:{../../../../../Documents/4th SEM/DSD/LAB/Lab1_ANDGate.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports Y]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports A]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports B]
